name: trener_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  percent_indicator: ^3.4.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  get_storage:
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: 6.1.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  youtube_player_flutter: ^8.1.2
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  pedantic: ^1.11.1
  carousel_slider: ^4.2.1
  file_picker: ^8.0.3
  appinio_video_player: ^1.2.0
  dio: ^5.4.3+1
  video_player: ^2.6.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1



flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/img/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf

